### ISSUE TITLE
How to structure this repo?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/tutorials#1]
Per tutorial type:

```
installation
gis
data-handling
style-guides
```

Per language:

```
R
- installation
- data-handling
- style-guide
Python
- installation
- data-handling
- gis
- style-guide
```

**Comment by ThierryO** [comment]
In case of installation I'd use a softwarename_usertype naming scheme. E.g. R_admin or python_user

**Comment by stijnvanhoey** [comment]
I agree with Thierry on the tutorial-type based structure to combine topics. So for example, when providing a tutorial on the usage of leaflet on both R and python, I would put it in the `gis`-folder: `R_leaflet` and `python_leaflet`?

**Comment by peterdesmet** [comment]
OK. For sorting, would it make more sense to put the topic first?

    gis/leaflet-R.rmd
    gis/leaflet-python.rmd

**Comment by stijnvanhoey** [comment]
indeed

**Comment by ThierryO** [comment]
yep. first topic, then language. dash `-` or underscore `_`?

**Comment by stijnvanhoey** [comment]
`-`

**Comment by peterdesmet** [comment]
I'd like to continue using dash for all files and directories, since they can be expected to form URLs, for which dash is more natural. See e.g. practice in this repository: https://github.com/inbo/data-publication

**Comment by ThierryO** [comment]
The repository is now live as Github pages on https://inbo.github.io/tutorials. Use `rmarkdown::render_site()` to render all the Rmarkdown files. Note that all RMarkdown files must be in the root directory. Hence I've added prefixes to the files.

**Comment by peterdesmet** [comment]
Nice!
