### ISSUE TITLE
Check category in header is from provided list of categories

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/tutorials#103]
To overcome too much categories to classify the posts, a [list of categories](https://github.com/inbo/tutorials/blob/master/static/list_of_categories) is provided. As mentioned by @ThierryO would be good to have a failing CI check when provided category is not part of the existing list. Another, maybe more easy to setup, option is to describe in the PR template to the user to have a check.

**Comment by ThierryO** [comment]
Adding a TL;DR section to [create tutorial](https://inbo.github.io/tutorials/create_tutorial/) would be useful too.

**Comment by stijnvanhoey** [comment]
Please provide this request in a new issue, as this is not related to the header category automated check or feel free to do a PR to improve the existing page..

**Comment by peterdesmet** [comment]
Merging this issue with #104
