### ISSUE TITLE
Add pull request template with checklist for submitting a tutorial

### ISSUE THREAD

**Issue by ThierryO** [inbo/tutorials#104]
The [create tutorial](https://inbo.github.io/tutorials/create_tutorial/) is quite long. A TL;DR section should summarise the key requirements for the tutorials. It can assume that the reader knows about git, github, Rstudio, ... If they don't than they can read the full document.

**Comment by peterdesmet** [comment]
For info on PR templates, see https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository. Create it as `.github/pull_request_template.md`

**Comment by peterdesmet** [comment]
From #103, also mention:

> Another, maybe more easy to setup, option is to describe in the PR template to the user to have a check [on included post categories]

**Comment by peterdesmet** [comment]
@ThierryO can you give the first go for this PR tutorial submission checklist? I can review it.

**Comment by peterdesmet** [comment]
Or rather, the first person from @inbo/oscibio @inbo/bmk that submits a tutorial can start listing things on this checklist.
