### ISSUE TITLE
remove old netlify site

### ISSUE THREAD

**Issue by ThierryO** [inbo/tutorials#106]
the old site is still being refered to

**Comment by stijnvanhoey** [comment]
As you mentioned in earlier correspondation (mail):

> Ik stel voor om de netlify site gewoon te dumpen i.p.v. een site met enkel een redirect te maken. Ik zal hem dumpen nadat je de nieuwe site gelanceerd hebt (= aangekondigd naar het INBO)

For the announcement, @ToonVanDaele is taking care of it.

**Comment by ThierryO** [comment]
@ivyjansen old site was replaced by a single page that redirects to the new site.

@stijnvanhoey following redirects are in place

    /installation/administrator/* https://inbo.github.io/tutorials/installation/administrator/ 301
    /installation/user/* https://inbo.github.io/tutorials/installation/user/ 301
    /installation/* https://inbo.github.io/tutorials/installation/ 301
    /data-handling/* https://inbo.github.io/tutorials/tutorials 301
    /package/* https://inbo.github.io/tutorials/tutorials 301
    /spatial/* https://inbo.github.io/tutorials/tutorials 301
    /styleguide/* https://inbo.github.io/tutorials/tutorials 301
    /git/* https://inbo.github.io/tutorials/tutorials 301
    /literature/* https://inbo.github.io/tutorials/articles 301
    /* https://inbo.github.io/tutorials 301
