### ISSUE TITLE
hugo deprecation warnings during current build of the website

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/tutorials#115]
These warnings are returned by the build process:

```
Building sites … WARN 2019/04/16 08:00:38 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/04/16 08:00:38 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
WARN 2019/04/16 08:00:38 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
```
As most warnings are direct effect of the used theme, we should patch the [minimo theme](https://github.com/MunifTanjim/minimo) directly when doing a fix.

**Comment by peterdesmet** [comment]
The errors disappear locally with the latest version of the theme `v2.9.0`:

```
git clone https://github.com/MunifTanjim/minimo.git --branch v2.9.0 themes/minimo
hugo server
```

@niconoe 

1. I think we should update to `2.9.0` in:

https://github.com/inbo/tutorials/blob/e16db19ae936631395e842000886def2c71df5c2/.github/workflows/deploy-gh-pages.yml#L22

2. And test any effects on the site

Note that I'm currently getting an additional error (v2.7.0 and v2.9.0):

```
Start building sites … 
ERROR 2021/06/22 13:59:32 [en] REF_NOT_FOUND: Ref "/categories/_index.md": "/tutorials/content/_index.md:15:16": page not found
```

**Comment by stijnvanhoey** [comment]
@peterdesmet when updating to hugo v0.84.1 and minimo theme 2.9.0, the issue can be fixed by using the permalink for categories registered in the config, e.g. `[Categories]({{< relref "#categories" >}})`

**Comment by niconoe** [comment]
I will investigate this soon.
