### ISSUE TITLE
styleguide R code: exceptions possible for lowercase?

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/tutorials#116]
Now that I started making a new INBO-package, I noticed in the styleguide R code that object names should be in lowercase.  But I actually prefer writing function names in lower case and other object names (vectors, tables,...) starting with a capital to make a clear distinction between these two.  In my opinion this makes the code more readable.

I don't want to force everyone to follow this rule, so I would suggest to allow both options (the current rule and an exeption to use one capital to make a distinction between different object types for readability).  I purposely follow the styleguide for function names, as users have to use these in their code (whereas they can easily switch to other object names and use their style).

Or we could generally agree to allow small style differences as long as the same style is consequently used through the whole package and does not vary too much from the suggested style?  (E.g. the LSVI-package, which I started developing before this styleguide was written, is in upper and lower camel case, and I understand this is too abberant from lowercase and underscores.)

Any opinions on this?

**Comment by peterdesmet** [comment]
If the function names (and their parameters!) are both lowercase, then your choice to capitalize object names doesn't affect users, but only contributors to the lsvi package, so that is good. Personally, I don't see a compelling reason to capitalize object names and haven't seen this used in other packages either. :smile:

**Comment by ElsLommelen** [comment]
Eh, for clarity, my question refers to new packages, I won't change the style of the LSVI-package:
- the development of the package started before the styleguide was written and the styleguide mentions: 'don't apply the style guide tot existing code'
- changes in the LSVI-package will affect code of 10+ users (and some more users are already familiar with the function names...)

(To be honest, I learned the coding style with capitalizing objects in Java and as I was used to it, I took it over when I started programming in R.  ;-) )

**Comment by ThierryO** [comment]
UpperCamelCase is seldom used in R. See http://www.sumsar.net/files/academia/UseR_2013_R_naming_conventions_final.pdf

using snake_case for both functions and parameters (both are objects!) allows to check the coding style using [lintr](https://github.com/jimhester/lintr) out of the box. lintr can be tweaks to prefer lowerCamelCase over snake_case, but again you'll have to use this for all objects.

**Comment by ElsLommelen** [comment]
What I learnt from the document you refer to, is that it's not unusual to use different styles for functions and parameters in R.  Using the same style for both has indeed an advantage for automatic code style checking, but to me this seems a minor argument compared to a higher readability when having a clear distinction between functions and parameters throughout the code.

After reading the document, I'm also wondering: why did we choose for snake_case in our style and not one of the more popular styles (lowerCamelCase or dot.separated)?

@peterdesmet's suggestion to give function parameters the same style as functions and change the style of the parameters inside the functions seemed a good idea to me, but a first try-out learned me this is likely to become a mess...  Using different styles for parameters in one script is likely to lead to an inconsistent style, as it makes it impossible to check for consistency.

**Comment by peterdesmet** [comment]
`snake_case` is advised by [tidyverse style guide](https://style.tidyverse.org/syntax.html#object-names). This guide is used for tidyverse packages (thus very consistent there) and also advised by rOpenSci, which I consider two trusted communities for this type of advise.

**Comment by ThierryO** [comment]
Renaming function arguments inside the function is a recipe for disaster. It creates a lot of unnecessary code, makes the code much harder to read and debug, and wastes a lot of memory. Don't do that. Ever.

If you want to update the coding style of a package, then write a new function in the new style. Rewrite the old function so it calls the new function and mark the old function as [`Deprecated`](https://www.rdocumentation.org/packages/base/versions/3.5.3/topics/Deprecated)

**Comment by ThierryO** [comment]
`snake_case` is the default in `lintr`, which follows the tidyverse styleguide

**Comment by ElsLommelen** [comment]
Ok, I guess I'll try out the recommendations of our styleguide for my new package: lowercase for all objects: parameters with underscores and functions with dots.  Looks like a confusing combination to me, but I'll see.

(As already mentioned: my other packages will stay as they are, I see no reason for updating them, as the styleguide should only be applied to new packages and it would be a lot of work.)

**Comment by peterdesmet** [comment]
> Function names with dots

I would also use `lower_case` for function names. I wasn't aware, but the style guide indeed says "function names with a single dot are allowed", but I would remove that. @ThierryO?

**Comment by stijnvanhoey** [comment]
Considering #118, I actually would close this issue and agree on the community standards provided by tidyverse/ropensci, without exceptions. It would be much harder to maintain and agree on our own standards, whereas connecting our style with those communities will increase consistency (both within INBO packages as with the community).

**Comment by ElsLommelen** [comment]
Ok to have lower_case for function names, but then I would like to have another possibility to distinguish between functions and parameters.  Maybe lowerCamelCase for parameter names?

**Comment by ThierryO** [comment]
single periods must be allowed as it is required for the S3 dispatch method. `summary(some_object)` will call `summary.class_of_some_object()`. E.g. `summary(my_linear_model)` is shorthand for `summary.lm(my_linear_model)`.

This should be the only reason for using dots in a **object** name. All other object names should follow the styleguide and use `snake_case`. Both _functions_ and _parameters_ are **objects**.

Give all objects a good name. If you need coding style to distinguish functions from parameters then you need to rethink the names.

Closing this issue after consulting @ElsLommelen
