### ISSUE TITLE
Links not working in `r_beginners` tutorial

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/tutorials#123]
When checking the updates on the [r_beginners](https://inbo.github.io/tutorials/tutorials/r_beginners/) tutorial, I encountered several broken links to the material. Some examples are [dplyr.pdf](https://inbo.github.io/tutorials/tutorials/r_beginners/src/dplyr.pdf), [dplyr_code.R](https://github.com/inbo/tutorials/blob/master/content/tutorials/r_beginners/src/dplyr_code.R), [dplyr_oefening](https://inbo.github.io/tutorials/tutorials/r_beginners/src/dplyr_oefening.pdf). For some of them I do not know which url it should actually redirect, but for the latter, I do think the link should be https://inbo.github.io/tutorials/tutorials/r_beginners/Les3/Scripts/Les3_huistaak.pdf

**Comment by ThierryO** [comment]
This is fixed
