### ISSUE TITLE
Review match names with GBIF tutorial 

### ISSUE THREAD

**Issue by peterdesmet** [inbo/tutorials#134]
Review https://inbo.github.io/tutorials/tutorials/r_gbif_name_matching/ to see if it still works with the new version of inborutils.

At the end of the tutorial, mention:

> For Python users, there is a similar (but no longer maintained) [function](https://github.com/inbo/inbo-pyutils/tree/master/gbif/gbif_name_match) in `inbo-pyutils`.

**Comment by damianooldoni** [comment]
Done. Issue can be closed.
