### ISSUE TITLE
Show authors of tutorial

### ISSUE THREAD

**Issue by peterdesmet** [inbo/tutorials#151]
Currently not shown, see e.g. https://inbo.github.io/tutorials/tutorials/r_gbif_name_matching/ vs https://github.com/inbo/tutorials/blob/ef3dc6859ca88583ae009edf86d55d6ba9630d1d/content/tutorials/r_gbif_name_matching/index.Rmd#L3

**Comment by florisvdh** [comment]
Mentioning the authors is better indeed.

**Comment by niconoe** [comment]
This is now in progress. Works fine, but take some time to update all author fields / create a file for each (that's how Hugo and the minimo theme want it to be).

**Comment by florisvdh** [comment]
Solved by @niconoe in #239.
