### ISSUE TITLE
Articles on website are not ordered by date

### ISSUE THREAD

**Issue by florisvdh** [inbo/tutorials#155]
See https://inbo.github.io/tutorials/articles/ -- the latest one is not at the top but at the bottom.

**Comment by peterdesmet** [comment]
@niconoe would you be able to investigate this?

**Comment by niconoe** [comment]
Absolutely. Thanks for your patience, adding this to my 2021 to-do list

**Comment by florisvdh** [comment]
Solved by @niconoe in #276. Thanks!
