### ISSUE TITLE
Structure images

### ISSUE THREAD

**Issue by peterdesmet** [inbo/tutorials#16]
In https://github.com/inbo/tutorials/pull/15 an img/ directory is added. I think we need to think how we want to structure these:

1. One img/ directory with all images for all tutorials. Best to have consistent naming, so we can see which image is for which tutorial
2. One directory per tutorial in the img/ directory (with same name). File names can be somewhat looser

I would prefer option 2

**Comment by ThierryO** [comment]
Let's keep things a simple as possible.

- images created at runtime: use the default location as setup by knitr. This will be something like _tutorial_name_/figures_html. Filename depends on the chunk name. 
- static images should go in the _tutorial_name_/img.

**Comment by stijnvanhoey** [comment]
As a question, how does static images should be handled to make sure they are correctly handled by the conversion to html? Apparently, the html file contains currently the absolute path instead of the relative path even thought they were defined relative in the source Rmarkdown?

**Comment by peterdesmet** [comment]
This relates to static images only. @ThierryO, you propose `tutorial_name/img`: do you mean we should put static images in the generated `docs/tutorial_name(/img)` folder? That breaks the concept of separating source from generated output.

**Comment by peterdesmet** [comment]
Ok, that makes sense. The one thing that still bothers me then, is that the tutorial itself is not placed in that folder:

```
data-handling-database-R/ (folder for images)
data-handling-database-R.Rmd (tutorial itself)
data-handling-googlesheet-R.Rmd (tutorial without images)
```

Rather than:

```
data-handling-database-R/ (folder with tutorial and images)
data-handling-googlesheet-R/ (folder with tutorial)
```

Which keeps things cleaner.

**Comment by stijnvanhoey** [comment]
Could we not just put the images in a tutorial specific subfolder for images, while including both the tutorial name and img-part in the file name?

```
data-handling-database-R-img/ (folder for images)
data-handling-database-R.Rmd (tutorial itself)
data-handling-googlesheet-R.Rmd (tutorial without images)
```

**Comment by ThierryO** [comment]
I'd go for this

```
data-handling-database-R/ (folder for auxiliary files)
data-handling-database-R.Rmd (tutorial itself)
data-handling-googlesheet-R.Rmd (tutorial without auxiliary files)
```

**Comment by peterdesmet** [comment]
Agreed, and that folder can contain data files, image files, etc. with names as we please.

**Comment by stijnvanhoey** [comment]
For the new version, we agreed on the 1 tutorial = 1 directory with all required images etc. in that directory. Closing here.
