### ISSUE TITLE
Latest website build failed

### ISSUE THREAD

**Issue by florisvdh** [inbo/tutorials#161]
Travis build #431 errored (triggered after merged PR #160).

It seems to go wrong in line 318:

```
$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.10.15
1 gem installed
invalid option "--token="
failed to deploy
```

**Comment by peterdesmet** [comment]
Issue resolved: variable `GITHUB_TOKEN` was still named `GH_TOKEN` in Travis.
