### ISSUE TITLE
every INBO R user should be able to run all code

### ISSUE THREAD

**Issue by ThierryO** [inbo/tutorials#17]
Currently https://github.com/inbo/tutorials/blob/master/source/data-handling-database-R.Rmd fails to run on my Linux machine. This implies that I can't update the other tutorials because one build fails.

**Comment by stijnvanhoey** [comment]
@ThierryO is there an option to exclude some of the tutorial files to rerun with a render_site command? It would help to have a temporary workaround.

**Comment by ThierryO** [comment]
That's not an option. Everybody would need to set that up individually. And probably redo that each times you work on a new branch. Currently it is only one file but that number is likely to increase.

A better solution would be to have the rendering done via CI.

contra:
- need to setup and maintain CI

pro:
- contributors compile only the files they are working on, not the gazillion other tutorials
- contributors don't have to update the rendered files because the CI does that. No more problems due to a contributor who forgot to render and commit the changes.
- only the CI needs all tools and access to render all the tutorials
- possibility to avoid merging PR to master that don't work (on CI)
- possibility to have all the rendered stuff in a `gh-pages` branch which makes for a cleaner repository

**Comment by stijnvanhoey** [comment]
The 1 tutorial = 1 directory with an md-file as specific input for the website in the new version solves this issue. Moreover, CI will be setup to keep website up to date.
