### ISSUE TITLE
Git Large File Storage

### ISSUE THREAD

**Issue by hansvancalster** [inbo/tutorials#181]
I think a tutorial on how / when to use [git large file storage](https://git-lfs.github.com/) would be good to have.  See also https://github.com/inbo/tutorials/pull/176#issuecomment-652802364

To decide when to use it, see the top answer [in this thread](https://stackoverflow.com/questions/49018053/how-large-does-a-large-file-have-to-be-to-benefit-from-git-lfs#:~:text=Version%20large%20files%E2%80%94even%20those,files%20on%20a%20remote%20server).

**Comment by peterdesmet** [comment]
GLF and artefacts are currently clogging the available free storage we have (see https://github.com/inbo/tutorials/issues/251) and we have no intent of increasing or promoting this. We typically have better systems to store INBO data than GitHub. Decided in meeting of June 22 to not create such a tutorials.
