### ISSUE TITLE
Tutorial read data from google sheets: use package googlesheets4 

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/tutorials#190]
The tutoral to [read data from google sheet](https://inbo.github.io/tutorials/tutorials/r_google_sheets/) makes use of the package `googlesheets`. However, this renders an error:

> Sign in with Google temporarily disabled for this app

This can be resolved by using the newer package `googlesheets4` ([link to GitHub](https://github.com/tidyverse/googlesheets4))

**Comment by florisvdh** [comment]
Good catch @LienReyserhove . A straightforward fix could be to replace the body of the tutorial with a link to the main `googlesheets4` vignettes, as these are fine tutorials! Example: https://googlesheets4.tidyverse.org/articles/articles/read-sheets.html And of course, we could contribute to / review those tutorials.

**Comment by florisvdh** [comment]
Solved by #204 and tutorial is [online](https://inbo.github.io/tutorials/tutorials/r_google_sheets/)!
