### ISSUE TITLE
use `sf` instead of `sp` package in points in polygon tutorial

### ISSUE THREAD

**Issue by hansvancalster** [inbo/tutorials#199]
See https://github.com/inbo/tutorials/pull/197#issuecomment-695949495

**Comment by hansvancalster** [comment]
This issue can be closed. The tutorial already shows how to do this with `sf` and `sp` - with the recommendation to use `sf`.

**Comment by florisvdh** [comment]
OK. Currently it is expected that `sp` will be 'retired' around 2024 (I understand that it would still exist but its functions would reroute to `sf`, in order to keep old code working). At that time we could do another update of all tutorials by dropping remaining `sp` code.
