### ISSUE TITLE
Limitations of Hugo + gfm for authoring tutorials

### ISSUE THREAD

**Issue by florisvdh** [inbo/tutorials#200]
In the tutorials website it is seen that citations (when using YAML key `link-citations: true`) and footnotes are not properly _linked_ to a target.

- in the case of footnotes, a rather awful plain (non-superscript) "[1]" is generated for footnote nr. 1, which is repeated at the bottom (this is hard-coded as such in in `index.md`, which does not implement pandoc's markdown syntaxis for footnotes) Compare to pandoc's markdown, which causes hyperlinked + superscript footnotes in html.
  - example of current result: 
![afbeelding](https://user-images.githubusercontent.com/19164640/93853877-f8667b00-fcb4-11ea-8adb-bf4536844395.png)

- in the case of citations, a hyperlink is created in the citation (clickable year), but it has no working target to a bibliography entry.
  - example non-working citation link: https://inbo.github.io/tutorials/tutorials/spatial_crs_coding/#ref-bivand_migration_2020

I think both problems occur because the _gfm_ format, according to pandoc documentation, does not support several extensions that _pandoc's markdown_ does support (see the [extensions](https://pandoc.org/MANUAL.html#extensions) section of the pandoc manual). For example, extensions [`footnotes`](https://pandoc.org/MANUAL.html#footnotes) and [`citations`](https://pandoc.org/MANUAL.html#citations). 

From https://pandoc.org/MANUAL.html#markdown-variants :

>Note, however, that commonmark and gfm have limited support for extensions. Only those listed below (and smart, raw_tex, and hard_line_breaks) will work. The extensions can, however, all be individually disabled. Also, raw_tex only affects gfm output, not input.
>
> gfm (GitHub-Flavored Markdown)
    pipe_tables, raw_html, native_divs, fenced_code_blocks, auto_identifiers, gfm_auto_identifiers, backtick_code_blocks, autolink_bare_uris, space_in_atx_header, intraword_underscores, strikeout, task_lists, emoji, shortcut_reference_links, angle_brackets_escapable, lists_without_preceding_blankline. 

Hence, for footnotes and citations to be functional, it would be great if pandoc's markdown could be used instead of `gfm`. @peterdesmet can you explain on the capabilities of the site-generator regarding pandoc's markdown? I think that all tutorials use `gfm` (or the deprecated `markdown_github` format), but I'm not sure whether that is a prerequisite? If so, it would be nice to have better solutions.

**Comment by florisvdh** [comment]
> it would be great if pandoc's markdown could be used instead of `gfm`

It was found today (8bcc90b) that Hugo supports pandoc's custom [heading identifiers](https://pandoc.org/MANUAL.html#heading-identifiers) (e.g. in `# My heading {#foo}`), i.e. if these are inserted directly in an `index.md` file. However, the `gfm` flavour itself does not support these, so when knitting an `index.Rmd` (with markdown output variant set to `gfm`) containing `# My heading {#foo}`, `{#foo}` is just dropped in the `index.md` file, hence links to `#foo` won't work. In other words, the workflow with gfm + hugo insists on using standard `#anchors-autogenerated-from-the-whole-title`.

Also, `<a name="foo"/>` is not honoured by Hugo when inserting that in `index.md`.

**Comment by peterdesmet** [comment]
> I think that all tutorials use `gfm` (or the deprecated `markdown_github` format), but I'm not sure whether that is a prerequisite? If so, it would be nice to have better solutions.

Yes, that is now uniformly done in #285.

Regarding the custom anchors:

- `variant: gfm` drops custom anchors when knitting
- `variant: gfm+header_attributes` creates error "The extension header_attributes is not supported for gfm" (note that `definition_list` seems to work and is used in [one tutorial](https://github.com/inbo/tutorials/blob/d28ec9376be40293d8151bdc2be772cdbb4a0fd2/content/tutorials/r_citations_markdown/index.Rmd#L15))
- Dropping `variant` still drops custom anchors (since the [default](https://rmarkdown.rstudio.com/docs/reference/md_document.html) is `markdown_strict`)
- `variant: markdown` retains custom anchors when knitting 🎉 

So, we could opt to use `variant: markdown` for all tutorials. I don't know if there will be any side effects.

**Comment by peterdesmet** [comment]
@florisvdh so far I notice two changes when using `markdown` over `gfm`:

- yaml properties are listed alphabetically (is fine)
- Bibliography is removed when I knit https://github.com/inbo/tutorials/blob/master/content/articles/communicating/index.Rmd
- References change from `Ellis & Leek (2017)` to `@ellis_how_2017`

So not ideal.

Can you try knitting with `markdown` and see if you encounter any important differences

**Comment by florisvdh** [comment]
Thanks for investigating @peterdesmet and sorry for the late reply.

I just finished some experiments as well, see a few commits in temporary branch `test_gfm_footnotes_citations`. Indeed, `markdown` just returns Pandoc's markdown which is supposed to be processed by Pandoc, which Hugo doesn't do. Hence the non-converted `@ellis_how_2017`.

Conclusions after experimenting:

- I suggest to at least use **`gfm+footnotes`** everywhere for the `md_document` variant. Instead of unlinked, plain `[1]` inline footnotes, it gives nice hyperlinked footnotes that work when clicking (see e95d3562 for effect on `index.md`):

![afbeelding](https://user-images.githubusercontent.com/19164640/145052065-f7f1e1bd-13c8-4f70-86eb-fde6bf411903.png)

- Optionally, one can add the YAML header key: `link-citations: true` and in the `index.md` this will effectively result in creating hyperlinked citations, with anchors repeated in a `div` tag in the bibliography, so that 'normal' processing to HTML should be successful (42a404e9). However it seems that **Hugo** doesn't cope well with the `div` tags in the bibliography. We do get hyperlinked citations, but they just don't work when clicking:

![afbeelding](https://user-images.githubusercontent.com/19164640/145052720-147a7f95-4968-4b12-baaf-60f96fa2ec54.png)

Any idea how to solve the latter, perhaps on the Hugo side?

**Comment by peterdesmet** [comment]
No, not familiar enough with the Hugo machinery. At least the footnotes will be solved in #285.

**Comment by florisvdh** [comment]
Will consider this closed by #285.

The linked citation subject (above) remains a challenge. Always welcome to tackle that too, but perhaps it's just not possible with Hugo (?).
