### ISSUE TITLE
Comments on git hands-on session

### ISSUE THREAD

**Issue by ThierryO** [inbo/tutorials#21]
Refers to #20 

- useRs will prefer to use git in RStudio. I expect that a large number of INBO git users will be useRs
- suggesting vim as editor is rather evil
- I'd start teaching based on user workflow maximising the use of the GUI in favor of the command line when the workflow permits
     - RStudio workflow for useRs
     - GitHub desktop for non R users
     - pure command line for code junkies
- I'd create pull requests only online
- update local master via `git pull` instead of `git fetch + merge`
- mention the `alias` only in the code junkie workflow. It is distracting for the beginners.
- RStudio allows you to commit a selection of changes in a file. That is handy to split changes over several commits.
- recommend a branching scheme depending on the complexity of the project.

**Comment by stijnvanhoey** [comment]
I'll certainly take these considerations into account for a (INBO-only) follow-up course. As the public of today is a mixed audience with a large number of command-line-rs, the setup of today is to provide both options for each action. I already agree that we probably better split GUI and non-GUI in different manuals as you suggest (Rstudio, Github Desktop and cmd).

**Comment by stijnvanhoey** [comment]
Most adaptations were taken into account in the Rstudio version of the course material in https://github.com/inbo/git-course closing here, further discussion can be done in that repo
