### ISSUE TITLE
Make the content compatible with recent Hugo versions

### ISSUE THREAD

**Issue by niconoe** [inbo/tutorials#226]
While working on #225, I tried to locally built the website with the most recent Hugo version (0.80), but was unable since apparently the content is not compatible with it. I had to download the old 0.62 release (the same that was used on Travis-CI) to be able to build it.

That's not a very sexy task, but the longer we wait, the harder it'll be :)

**Comment by florisvdh** [comment]
Indeed, it will be better to do that. :+1:

**Comment by stijnvanhoey** [comment]
@niconoe see my comment on https://github.com/inbo/tutorials/issues/115#issuecomment-868413595 I tested with hugo v0.84.1 and it works for the Fluves version of tutorials website - which is very similar ;-)
