### ISSUE TITLE
add qpdf installation instructions to admin installation

### ISSUE THREAD

**Issue by hansvancalster** [inbo/tutorials#240]
As noted here: https://github.com/inbo/n2khab/pull/118#issuecomment-802651711, the program qpdf is necessary to run `devtools::check()`. 
I had the same issue on a new laptop with Windows 10, so I'm guessing other people will run into it as well. 
Therefore my suggestion is that the the [qpdf program](https://sourceforge.net/projects/qpdf/files/) be installed on all recent laptops where R is installed.
We just need to describe the installation instructions, which involves:

- download [qpdf program](https://sourceforge.net/projects/qpdf/files/) 
- unpack and copy files to C:/Program Files/
-  add 'C:/Program Files/qpdf-<version_numer>/bin' to the system PATH environmental variable 

Admin rights are needed.

**Comment by ThierryO** [comment]
Good suggestion.

**Comment by hansvancalster** [comment]
This issue can be closed. The installation scripts maintained by @wimdp to update/install `R` and `RStudio`, now also install `qpdf` software on computers in our organisation.
