### ISSUE TITLE
Link 'improve this page' should go to edit page instead of blob

### ISSUE THREAD

**Issue by florisvdh** [inbo/tutorials#258]
I thought that once the 'improve this page' link did go to the edit page, but currently it returns the blob.

E.g. it now goes to:

https://github.com/inbo/tutorials/blob/master/content/tutorials/r_setup_codingclub_session/index.Rmd

instead of:

https://github.com/inbo/tutorials/edit/master/content/tutorials/r_setup_codingclub_session/index.Rmd

Anyway I suggest the link goes to the edit page directly, which is easier for beginners.

**Comment by niconoe** [comment]
I will try to solve that one!
