### ISSUE TITLE
Add license to the published (i.e. rendered) tutorials

### ISSUE THREAD

**Issue by florisvdh** [inbo/tutorials#268]
A choice has been made to add a CC-BY license to all our published tutorials, as is the case for all INBO publications. So the license is to be made visible on the tutorials website, preferably in each tutorial.

For the implementation, the [gitbook_en.html](https://github.com/inbo/INBOmd/blob/0.4.10/inst/css/en/gitbook_en.html) template of the INBOmd html report (currently in 0.4.10 branch) may be inspiring (currently still has CC-BY-SA, will be CC-BY). It has the license logo at the top and a more complete mention with authors in a footer. (This approach will be followed for the INBO protocols website, which is created with Rmarkdown.)

Can OSCIBIO include this when reworking the website?

AFAIK this may be regarded distinct from source code licensing, i.e. the repository license, although in the case of publication's source code (markdown) it may be more logical to use CC-BY for the repo as well.

**Comment by peterdesmet** [comment]
@florisvdh the link you mentioned is broken and the protocols website does not seem to be online yet. So I don't have an example of what you have in mind. I suggest I:

- Include a CC-BY logo in the website footer (only). That is generally where users look for licenses.
- Update the LICENSE of the repository

Does this sound good for you?

**Comment by peterdesmet** [comment]
I don't have much control over the layout, but this is how it would look like:

<img width="1059" alt="Screenshot 2021-11-17 at 17 15 05" src="https://user-images.githubusercontent.com/600993/142238387-aa0d7d8e-1e17-46fb-aeaf-0b46da1c7bb5.png">

**Comment by florisvdh** [comment]
The layout in the screenshot is OK to me; is it added to all pages?

Is it correct to assume that CC-BY, in a tutorial's footer, comes down to a request to cite the _tutorial authors_, despite INBO being mentioned as copyright holder next to the CC-BY icon? Then preferably the copyright mention starts at a new line?

@ThierryO if you'd like to suggest alternatives to @peterdesmet feel free to point to currently applicable template code in INBOmd / protocolsource repositories. Not sure whether it can be used with Hugo though. @peterdesmet I think the current gitbook layout of an INBO HTML report can be seen at https://inbo.github.io/inbomd_examples/.

**Comment by peterdesmet** [comment]
> The layout in the screenshot is OK to me; is it added to all pages?
Yes, added to all pages.

> Is it correct to assume that CC-BY, in a tutorial's footer, comes down to a request to cite the tutorial authors, despite INBO being mentioned as copyright holder next to the CC-BY icon? Then preferably the copyright mention starts at a new line?
No, without a clear suggested citation users will likely interpret that as citing INBO rather than the tutorial authors. I personally think that is fine: I'd already be happy if our tutorials get linked to and INBO is mentioned. If we want to make it stricter, we have to update the default theme to include an automatically build citation for every tutorial. Not sure that is worth it.

**Comment by peterdesmet** [comment]
PR made in https://github.com/inbo/tutorials/pull/286

**Comment by florisvdh** [comment]
Solved in #286; thank you Peter!
