### ISSUE TITLE
Functionality to quickly export all raster layers from a `filegdb`

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/tutorials#29]
`Filegdb` is a format regularly used, for both rasters and vectors. However, the *reading of rasters from a filegdb* towards other environments (e.g. R) is not supported by the existing drivers of GDAL and it does not seem to be supported in the near future. 

It would be good to have a short tutorial of explanation that simplifies the extraction of all raster-layers from a `filegdb` to individual raster files (e.g. geotiff), making these data readable for other applications.

**Comment by stijnvanhoey** [comment]
To clarify: the [`OpenFileGDB`](http://www.gdal.org/drv_openfilegdb.html) driver has been reverse engineered and:
- reads vector data from a filegdb
- CAN NOT read raster data from a filegdb
- CAN NOT write any data to a filegdb

There is an alternative driver, [FileGDB](http://www.gdal.org/drv_filegdb.html), but 
- I'm unsure if this provides support for raster layers
- I'm unsure how to get these installed by the end-users or provide easy installation instructions
- there is still the license-dependency, as it uses the [filegdb-api](http://appsforms.esri.com/products/download/#File_Geodatabase_API_1.3)

Would it be an option to provide a small functionality in Arcpy that is capable to easily export layers from a filegdb and provide them as geotiff? Is this feasible for large raster data-layers?

**Comment by ThierryO** [comment]
Given that INBO has an [open data policy](https://www.inbo.be/nl/node/38611), we should use only open data formats.

**Comment by stijnvanhoey** [comment]
@ThierryO this request follows from the situation that users are currently using filegeodatabases in their (personal) workflow and looking for a solution to use their existing data (stored in a gbd) in other applications (e.g. R) as well. You're right about the open data format discussion, but I would leave this out of scope here.

**Comment by jeroendereu** [comment]
We will probably not be able to do this outside an ESRI-environment. 
[FileGDB](http://www.gdal.org/drv_filegdb.html) depends on the [ESRI File Geodatabase API](https://github.com/Esri/file-geodatabase-api/tree/master/FileGDB_API_1.5). Even in the most recent ESRI File Geodatabase API build (v 1.5, 02/03/2017), rasters are not supported yet.

**Comment by ThierryO** [comment]
@jeroendereu I would suggest for the GIS team to write a set of recommendations to ArcGIS users on which formats to use for storing their work. The formats should be at least readable through [GDAL](http://www.gdal.org/) and preferably also writable through GDAL. And a tutorial/tool on how to convert relevant other formats into the recommended formats.

**Comment by fredericpiesschaert** [comment]
@carinewils dag Carine, morgen is er opvolgingsoverleg ivm de tutorials, kan jij even een svz geven over dit ticket?  Ik sta ook bij de assignees maar heb hier niet veel mee te maken denk ik.

**Comment by carinewils** [comment]
Bij mijn weten is er buiten de ArcGIS omgeving nog steeds geen mogelijkheid
om rasters aan te spreken (of te exporteren) in/van een FileGDB.
