### ISSUE TITLE
python installation (on windows)

### ISSUE THREAD

**Issue by johanvdw** [inbo/tutorials#30]
It would be good if there is a standard tutorial on how to install python on windows.
Eg miniconda, conda-forge, ...

I'd like to refer to this in the installation instructions for niche_vlaanderen.

**Comment by johanvdw** [comment]
@stijnvanhoey ,

Next week (november 7) I will let the users test niche_vlaanderen. I've added some install instructions here: https://inbo.github.io/niche_vlaanderen/installation.html

Can you check this is compatible with what you have in mind?

**Comment by peterdesmet** [comment]
In my opinion, installing Python on Windows is too broad topic to cover as a tutorial: there is lots of (more up to date) information available elsewhere.
