### ISSUE TITLE
WFS services in R: small suggestion for example 5

### ISSUE THREAD

**Issue by cecileherr** [inbo/tutorials#304]
Small suggestion for 'Example 5: extract feature data at particular points':

> CQL_FILTER: Define the spatial operator, in this case `INTERSECTS` of the WFS `geom` and our `POINT` coordinate. The operators are enlisted in the `<ogc:SpatialOperators>` field.

It might seem obvious to you, but since it was not for me: I think it might be useful to add sthing like this: 

> `geom` is the name of the geometry field (in this example `geom` but other web services use `SHAPE`  (maybe add here the most common examples))

I thought  `geom` was some kind of reserved name...

**Comment by hansvancalster** [comment]
Good point! I will fix this
