### ISSUE TITLE
meaning of tl:dr: a typo?

### ISSUE THREAD

**Issue by damianooldoni** [inbo/tutorials#69]
In the beautiful tutorial `large-files-R.Rmd` there is a subsection called [tl;dr](https://github.com/inbo/tutorials/blob/master/source/data-handling/large-files-R.Rmd#tldr). I don't get the meaning of this name. A typo, maybe?
Thanks.

**Comment by stijnvanhoey** [comment]
Wikipedia is there for you: https://en.wikipedia.org/wiki/Wikipedia:Too_long;_didn%27t_read

**Comment by damianooldoni** [comment]
:nerd_face:
