### ISSUE TITLE
Add html anchors to section title

### ISSUE THREAD

**Issue by ThierryO** [inbo/tutorials#72]
That is what pkgdown does.It make it easy to share a link to as specific section. E.g. https://inbo.github.io/git2rdata/articles/storing_dataframe.html#usage-with-git-as-version-control-system

**Comment by stijnvanhoey** [comment]
I think this is default to hugo as well, e.g. https://inbo.github.io/tutorials/tutorials/spatial_wfs_services/#download-feature-attribute-data-from-wfs
or https://inbo.github.io/tutorials/installation/user/user_install_kerberos/#sql-database-connections

**Comment by ThierryO** [comment]
How does the user sees those linkable items? pkgdown makes it obvious when you hover over a section title. This is not the case with the current tutorials website.

**Comment by peterdesmet** [comment]
Could be added in css/templating of theme.
