### ISSUE TITLE
Remove theme from repo

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/tutorials#76]
@peterdesmet any theme adjustment you think would be appropriate; feel free to rock on it ;-). New theme is https://github.com/MunifTanjim/minimo which is [part of this repo](https://github.com/inbo/tutorials/tree/theme-update/themes/minimo). We could also check to keep the source code out of the repo and just use a link or add it to build setup?

**Comment by peterdesmet** [comment]
Note to self: look for similar themes that are build with bootstrap. Would make it much faster to implement things. If not, I’ll incorporate it in this theme.

**Comment by peterdesmet** [comment]
After looking at this I would:

- Keep the minimo theme
- Not change anything in the `/theme` directory (and thus revert https://github.com/inbo/tutorials/commit/036cfe57efaf325104ae20b5cd49ac3606d4fe0d#diff-ed46452c026fee2894508390d3f14b62), but remove that dir and link out to the theme. That removes clutter and confusion of what can be changed.
- Apply any necessary changes (including https://github.com/inbo/tutorials/commit/036cfe57efaf325104ae20b5cd49ac3606d4fe0d#diff-ed46452c026fee2894508390d3f14b62) in `layouts` (which seems to have precedence of layouts in the theme) and `custom.css`

**Comment by stijnvanhoey** [comment]
I agree with removing the theme itself out of the repo for further maintenance, but I was not able to inegrate the edits I did on theme level 036cfe5#diff-ed46452c026fee2894508390d3f14b62  intothe `layouts` folder. As the github-edit link was mentioned as an important feature, I would only ditch the theme adjustments when the alternative is working.

**Comment by peterdesmet** [comment]
Looks like I was able to do that in 62d391a (works for me locally at least). I have updated issue title.
