### ISSUE TITLE
helper script to check if each directory has an index.md

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/tutorials#77]
a helper script that reports:
- if for each Rmd an equivalent md exists would be useful
- if an md-file is not named `index.md`
- if multiple md files are in a directory

**Comment by damianooldoni** [comment]
This R script does the job. Do you have something like this in mind?

```r
#load library
library(here)
library(assertthat)

# get all paths with documents: tutorials and articles
list_tutorials_path <- list.dirs(path = here("content", "tutorials"), recursive = FALSE)
list_articles_path <- list.dirs(path = here("content", "articles"), recursive = FALSE)
list_documents_path <- c(list_tutorials_path, list_articles_path)

for (document in list_documents_path) {
  tutorial_files <- list.files(document, include.dirs = FALSE)
  
  # find md files
  md_file_pos <- grep("\\.md", tutorial_files)
  md_file <- tutorial_files[md_file_pos]
  
  # check if multiple md files are in a directory
  assert_that(length(md_file) <= 1,
              msg = paste0("Multiple md files found in ", document, "."))
  
  # check if md-files are not named index.md
  assert_that(all(md_file == "index.md"),
              msg = paste0("md file ", 
                          tutorial_files[md_file_pos],
                          " should be renamed index.md in ",
                          document,
                          "."))
              
  # check that for each Rmd an equivalent md exists
  rmd_file_pos <- grep("\\.Rmd", tutorial_files)
  rmd_file <- document[rmd_file_pos]
  if (length(rmd_file) > 0) {
    rmd_file <- tutorial_files[rmd_file_pos]
    assert_that(length(md_file) > 0, 
                msg = paste0("Rmd file ", 
                            rmd_file,
                            " not converted to markdown file in ", document, "."))
    }
}
```

If no error is arised, then it is all fine.

**Comment by ThierryO** [comment]
Note that `list.files` has a pattern argument and include.dirs is by default FALSE. That is more elegant and efficient to find md files.

    md_file <- list.files(document, pattern = "\\.md")

you don't need the all() in the second assertion. If there is more than one md file, then first assertion yields an error.

**Comment by damianooldoni** [comment]
Thanks @ThierryO! Yes, indeed, using `pattern` argument within `list.files` makes code shorter and more elegant. :+1: 

About the `all()`, I added as shortcut to avoid `Error: assert_that: length of assertion is not 1` for folder `.../tutorials/test_files` which has no `md files` or `Rmd files` neither. Actually no idea why this folder exists.

Code with `pattern` argument as suggested by @ThierryO:

```r
library(here)
library(assertthat)

list_tutorials_path <- list.dirs(path = here("content", "tutorials"), recursive = FALSE)
list_articles_path <- list.dirs(path = here("content", "articles"), recursive = FALSE)
list_documents_path <- c(list_tutorials_path, list_articles_path)

for (document in list_documents_path) {
  md_file <- list.files(document, pattern = "\\.md")
  
  # check if multiple md files are in a directory
  assert_that(length(md_file) <= 1,
              msg = paste0("Multiple md files found in ", document, "."))
  
  # check if md-files are not named index.md
  assert_that(all(md_file == "index.md"),
              msg = paste0("md file ", 
                          tutorial_files[md_file_pos],
                          " should be renamed index.md in ",
                          document,
                          "."))
              
  # check that for each Rmd an equivalent md exists
  rmd_file <- list.files(document, pattern = "\\.rmd")
  if (length(rmd_file) > 0) {
    assert_that(length(md_file) > 0, 
                msg = paste0("Rmd file ", 
                            rmd_file,
                            " not converted to markdown file in ", document, "."))
    }
}
```

**Comment by peterdesmet** [comment]
I guess this could be a (non-R script) that is part of GitHub actions, but on the other hand, I don't think we've encountered it before that people write tutorials without writing an `index.md`?

**Comment by ThierryO** [comment]
Add if there is both an `index.Rmd` and `index.md`, check if the `index.Rmd` was rendered. We did something similar with `README.Rmd` in  https://github.com/inbo/checklist/blob/867f045d2056daa5775dcb387f47ec6f2bbcadab/R/check_documentation.R#L76

**Comment by niconoe** [comment]
Thanks a lot, @ThierryO! We could indeed to that, but we'd need to set up an environment in GitHub Actions able to compile all `Rmd` files in various tutorials with guaranteed same byte-to-byte output than what authors generate on their machines prior to submission (but in that case, why are we asking them to provide the `md` files at all).

All in all, the more I think of this issue, the more I think it's probably not that easy to implement fully and properly, and given it's open for 3 years without (at my knowledge) encountering any practical issues due to this, I wonder if this issue really deserve to invest much time in it. Any opinion? @florisvdh? @peterdesmet? @damianooldoni?

**Comment by florisvdh** [comment]
Just providing my opinion on this:

- personally I don't see the need to re-check an already working website (hence to check the existence of `index.md` files). At the same time, just checking the presence of `index.md` files wouldn't be harmful nor difficult.
- checking the presence of `index.md` can as well happen manually while checking correctness and sensibility of a tutorial's contents
- there's an auto-build of the website in each PR which can be used as a further, manual check of the presence of an updated `index.md` for the PR's tutorial, when a reviewer looks at it
- automated (relatively unsupervised) creation of all `index.md` files on each push and PR to `main`, while sounding attractive to be sure no errors occur with current package versions, has some disadvantages compared to the current static case:
  - using new package versions, hence code output, would not match the tutorial's text and date any longer (except when using `renv` at tutorial level, but this complicates matters further). Even when tutorial's code may run without errors using new packages, this kind of mismatching will occur for sure, and it would need extra maintenance.
  - we have to outweigh proactive (by testing) vs. reactive maintenance (reactive: when a _reader_, not a bot, complains). Overall, automated knitting would invoke more frequent maintenance (including that of the testing system). I'm more in favour of a planned choice to manually update one or several outdated tutorials.

IMHO this issue can be closed, unless somebody is in favour of implementing something simple. The original idea is in fact simple, and it then involves e.g. a simple bash check inside a GHA workflow.

**Comment by niconoe** [comment]
Thanks a lot @florisvdh. I agree with all this, and I also think that automated creation of `index.md` files sounds attractive in theory, but would probably in practice create more troubles than it's solving.

So, I'd also close this issue. I'd be happy to implement a "simple solution" if we ever encounter a real-word issue with any of this in the future.
