### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by ThierryO** [inbo/tutorials#8]
Currently, the main page of http://inbo.github.io/tutorials is based on `README.Rmd`. I think it would be better to separate both. `index.Rmd` should have an introduction to http://inbo.github.io/tutorials and a reference to https://github.com/inbo/tutorials. Whereas `README.Rmd` should focus on the repository and just link to the rendered version on http://inbo.github.io/tutorials

**Comment by peterdesmet** [comment]
Agreed. And it should be `index.Rmd` and `README.md` (regular markdown, never to be included via bookdown).

**Comment by ThierryO** [comment]
Actually, there is only a `README.md` and no `README.Rmd` ;-)

**Comment by peterdesmet** [comment]
Great! Will you rerun bookdown so it's live at https://inbo.github.io/tutorials/?

**Comment by ThierryO** [comment]
We still have to change the content of `index.Rmd` and `README.md`.

**Comment by ThierryO** [comment]
handled in  976dd6ded89fc2d94bd1591d34c22ba79a4733d5 at PR #7
