### ISSUE TITLE
make links visible

### ISSUE THREAD

**Issue by ThierryO** [inbo/tutorials#82]
Links should be clearly visible to the visitors. At the moment many links are only visible when hovering over them. See  the list of tutorials in https://inbo.github.io/tutorials/tutorials/

**Comment by stijnvanhoey** [comment]
So, you refer to the following elements of the website (not about links inside the posts itself):

* [ ] menu items
* [ ] tags
* [ ] categories
* [ ] list overview of tutorials/posts 

I'm not really sure if it is really required to adapt the theme to make them stand out as link? Can you mark the items for which this would be really required? 

@peterdesmet what is your thought about this?

**Comment by ThierryO** [comment]
Mainly the list of overview of tutorials.

**Comment by stijnvanhoey** [comment]
@peterdesmet could we solve this by a small link icon after the text?
