### ISSUE TITLE
Links missing on installation pages

### ISSUE THREAD

**Issue by aaikedw** [inbo/tutorials#83]
This page reads "Check the administrator or user pages in function of the administrator rights on your computer.", but the corresponding links are missing on this page.

**Comment by stijnvanhoey** [comment]
Relative link to other pages not properly rendered, need to recheck this

**Comment by stijnvanhoey** [comment]
Fixed by 5987f35545d75555aaf352e7da6da56adfee7833 (travis was not building the master branch, but still theme-update branch, hm). Thanks for the valuable comment.
