### ISSUE TITLE
Add a style guide for SQL code

### ISSUE THREAD

**Issue by ThierryO** [inbo/tutorials#9]

**Comment by florisvdh** [comment]
:tada: see https://inbo.github.io/tutorials/tutorials/sql_styleguide/, coordinated by @fredericpiesschaert :+1: . Closing here!

**Comment by peterdesmet** [comment]
Very nice guide @fredericpiesschaert! It seems I follow the guide almost completely, except that I always indent:

```sql
SELECT
    t.field1
  , t.field2
FROM
  table1 as t
WHERE
  1 = 1
  AND field1 = "something"
```

Rather than:

```
SELECT t.field1
  , t.field2
FROM table1 as t
WHERE 1 = 1
  AND field1 = "something"
```

Is the first version used often and/or recommended?
