### ISSUE TITLE
Idea: overview list of interesting INBO-packages

### ISSUE THREAD

**Issue by florisvdh** [inbo/tutorials#93]
I think that a page ('article') with a simple (short)list could suffice. In order to provide one central overview of the main packages in which INBO has a large ownership / contribution and which are useful to many colleagues (and other people). The primary purpose then, is raising awareness. It could provide one or at most a few lines per package to characterize the package's purpose and provide a link to the package docs.

Examples probably include inborutils, INBOmd, INBOtheme, pydov, git2rdata, ... To be kept up to date.

What do you think?

**Comment by stijnvanhoey** [comment]
Having this overview is a great idea I think. From our team, the following R/python packages are probably in scope:

- [ ] https://github.com/ropensci/wateRinfo
- [ ] https://github.com/DOV-Vlaanderen/pydov
- [ ] https://github.com/inbo/pywhip
- [ ] https://github.com/inbo/niche_vlaanderen
- [ ] https://github.com/inbo/uvabits
- [ ] https://github.com/inbo/etn
- [ ] https://github.com/inbo/pyinaturalist
- [ ] https://github.com/inbo/inborutils

**Comment by florisvdh** [comment]
I'll see with the rest of my team to extend the list of packages, later this month.

**Comment by florisvdh** [comment]
The following packages are to be added:

- https://github.com/inbo/inbomd
- https://github.com/inbo/inboggvegan
- https://github.com/inbo/inbotheme
- https://github.com/inbo/git2rdata
- https://github.com/inbo/inlatools
- https://github.com/inbo/multimput
- https://github.com/ThierryO/grts

The provided link will be the documentation website, if available.

I will make a draft in a PR, for further review.

**Comment by florisvdh** [comment]
This has been realised some time ago: https://inbo.github.io/tutorials/articles/inbo_software/
