### ISSUE TITLE
Question: background on coordinate reference systems

### ISSUE THREAD

**Issue by florisvdh** [inbo/tutorials#95]
In 2014 I wrote a [document](https://drive.google.com/open?id=0B3UWqZg--TCoT19mUUdNMkgyekE) on theoretical and applied background of coordinate reference systems, in Dutch. Some introductory overview of common standards and open tools is also provided in the document. I'm still using it myself now and then to recall theory behind CRS's.

It has never been distributed or published really; it was some sort of spare time quest of myself and I've shared it with some colleagues at the time.

So, I'm wondering if this content should find its place on the tutorials website. E.g. as a (long!) article, but in Dutch. That would require some additional markdown tinkering, but that's not a point (the pandoc conversion seemed to run quite well). Another option for the website is to just mention the link to the pdf version. Still another option is that someone translates the whole thing in English - be my guest.

What do others think about it?

**Comment by stijnvanhoey** [comment]
The document provides a comprehensive summary of the `CRS` matter, with much more detail than other/typical online resources. By doing so, the document certainly provides value for a wider audience. Ideally, the text is translated to English, but I'm fine with a Dutch tutorial (converted as md file) as well.

My only suggestion would be to be combine it with a small `tl;dr` section with a set  _practical_ hands-on advices/tips.

**Comment by florisvdh** [comment]
Originally planned for 2020, but postponing this article/tutorial to a later (unknown) date when GDAL3 and PROJ>6 are used by default, given current migrations of CRS handling by R packages (#164). Instead, several non-planned geo-tutorials have been contributed in 2020.
